# Generated by Django 3.2.15 on 2022-08-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50)),
                ('time', models.TimeField(auto_now_add=True)),
                ('contents', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PostInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('contents', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=50)),
                ('time', models.TimeField(auto_now_add=True)),
                ('category', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50)),
                ('uid', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='auth',
            old_name='userId',
            new_name='uid',
        ),
        migrations.RemoveField(
            model_name='auth',
            name='email',
        ),
        migrations.AddField(
            model_name='auth',
            name='nickname',
            field=models.CharField(default='default', max_length=50),
        ),
    ]
