# Generated by Django 4.1 on 2022-08-14 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_comment_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='postIdList',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='board.comment'),
        ),
    ]
