# Generated by Django 4.1 on 2022-08-14 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_profile_postidlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='postIdList',
        ),
        migrations.AlterField(
            model_name='comment',
            name='nickname',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='board.auth'),
        ),
    ]
