# Generated by Django 4.1 on 2022-08-14 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_comment_post_id_alter_comment_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='commentUser',
            field=models.ForeignKey(db_column='commentUser', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentUser', to='board.auth'),
        ),
        migrations.AddField(
            model_name='postinfo',
            name='postUser',
            field=models.ForeignKey(db_column='postUser', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postUser', to='board.auth'),
        ),
    ]
