# Generated by Django 4.1 on 2022-08-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_remove_comment_post_id_comment_commentuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='uid',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
