# Generated by Django 4.1 on 2022-08-16 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_alter_auth_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentUser',
            field=models.ForeignKey(db_column='commentUser', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='board.auth'),
        ),
        migrations.AlterField(
            model_name='postinfo',
            name='postUser',
            field=models.ForeignKey(db_column='postUser', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='board.auth'),
        ),
    ]
