# Generated by Django 4.1 on 2022-08-17 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_postinfo_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commentedPost',
            field=models.ForeignKey(db_column='commentedPost', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentedPost', to='board.postinfo'),
        ),
        migrations.AlterField(
            model_name='likeinfo',
            name='likeUser',
            field=models.ForeignKey(db_column='likeUser', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likeUser', to='board.auth'),
        ),
    ]
