# Generated by Django 3.2.15 on 2022-08-30 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_comment_commentedpost_alter_likeinfo_likeuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='uid',
            field=models.CharField(max_length=50),
        ),
    ]
